robot_base_frame:       amiro/base_link
robot_radius:           0.1

update_frequency:       5.0
publish_frequency:      2.0
transform_tolerance:    0.1
resolution:             0.05

obstacle_range:         3.0
raytrace_range:         2.5

#layer definitions
static:
  map_topic:            map
  subscribe_to_updates: true

obstacles_laser:
  observation_sources:  laser
  laser: {data_type: LaserScan, topic: /amiro/laserscan, marking: true, clearing: true, inf_is_valid: true}

inflation:
    inflation_radius: 0.1
